### ISSUE TITLE
I couldn't run it, because I had a mistake, but I couldn't find the reason.

### ISSUE THREAD

**Issue by ERQQRR** [taolei87/sru#32]
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/THC/generic/THCStorage.cu line=66 error=30 : unknown error
Traceback (most recent call last):
  File "/home/lai/filespace/eclipse-workpplace/sru-master/language_model/train_lm.py", line 14, in <module>
    import cuda_functional as MF
  File "/home/lai/filespace/eclipse-workpplace/sru-master/cuda_functional.py", line 13, in <module>
    tmp_ = torch.rand(1,1).cuda()
  File "/home/lai/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 66, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/home/lai/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 269, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: cuda runtime error (30) : unknown error at /opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/THC/generic/THCStorage.cu:66

**Comment by mojesty** [comment]
What does `torch.cuda.is_available()` tell you?

**Comment by ERQQRR** [comment]
It's True
I made some attempts. When I delete "from cupy.cuda import function" in the cuda_functional module, the error will change, of course, it is only because the variable is missing.
but But I still don't know how to solve it

**Comment by mojesty** [comment]
Can you run any other model on cuda? Sometimes pytorch's `cuda` is quite unstable.

**Comment by ERQQRR** [comment]
You are right, the crux of the problem is CUDA,

I will reinstall CUDA and try it again

**Comment by ERQQRR** [comment]
Hi，I run it in the other computer ,and installed as a regular package via python setup.py install ，
`Traceback (most recent call last):
  File "/home/lai/workspace/sru/1.py", line 19, in <module>
    import cuda_functional as MF
ImportError: No module named 'cuda_functional'`
