### ISSUE TITLE
Weight and grad shapes mismatch

### ISSUE THREAD

**Issue by iasawseen** [taolei87/sru#60]
Hi!

I have some issues running language_model example. 

```
$ python3 train_lm.py --train train.txt --dev valid.txt --test test.txt 
Namespace(batch_size=32, bias=-3, clip_grad=5, d=910, depth=6, dev='valid.txt', dropout=0.7, lr=1.0, lr_decay=0.98, lr_decay_epoch=175, lstm=False, max_epoch=300, rnn_dropout=0.2, test='test.txt', train='train.txt', unroll_size=35, weight_decay=1e-05)

WARNING: set_bias() is deprecated. use `highway_bias` option in SRUCell() constructor.

WARNING: set_bias() is deprecated. use `highway_bias` option in SRUCell() constructor.

WARNING: set_bias() is deprecated. use `highway_bias` option in SRUCell() constructor.

WARNING: set_bias() is deprecated. use `highway_bias` option in SRUCell() constructor.

WARNING: set_bias() is deprecated. use `highway_bias` option in SRUCell() constructor.

WARNING: set_bias() is deprecated. use `highway_bias` option in SRUCell() constructor.
vocab size: 10000
num of parameters: 24026720
train_lm.py:110: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  norms = [ "{:.0f}".format(x.norm().data[0]) for x in self.parameters() ]
        p_norm: ['100', '45', '90', '45', '90', '45', '90', '45', '90', '45', '90', '47', '90', '0']

SRU loaded for gpu 0
train_lm.py:140: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  torch.nn.utils.clip_grad_norm(model.parameters(), args.clip_grad)
Traceback (most recent call last):
  File "train_lm.py", line 262, in <module>
    main(args)
  File "train_lm.py", line 206, in main
    train_ppl = train_model(epoch, model, train)
  File "train_lm.py", line 145, in train_model
    p.data.add_(-lr, p.grad.data)
RuntimeError: expand(torch.cuda.FloatTensor{[2, 910]}, size=[1820]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)
```

It looks like it is because some weight and grad has different shapes.

**Comment by taolei87** [comment]
Hi, could you do a `git pull` and try again?  It is probably now compatible with new pytorch version.

**Comment by iasawseen** [comment]
It works. Thanks!

**Comment by taolei87** [comment]
u r welcome!
