### ISSUE TITLE
AttributeError: 'Program' object has no attribute '_program'

### ISSUE THREAD

**Issue by anis016** [taolei87/sru#63]
Hello!

I am trying to work with SRU in DrQA. However, when I run the train method I get the following error

Python version: 3.6
CUDA: 9.0 and GPU supported

```
Traceback (most recent call last):
  File "/home/ghostrig/Python_Workspace/deep-learning/others/DocReaderQA/train.py", line 14, in <module>
    from drqa.model import DocReaderModel
  File "/home/ghostrig/Python_Workspace/deep-learning/others/DocReaderQA/drqa/model.py", line 15, in <module>
    from .rnn_reader import RnnDocReader
  File "/home/ghostrig/Python_Workspace/deep-learning/others/DocReaderQA/drqa/rnn_reader.py", line 10, in <module>
    from . import layers
  File "/home/ghostrig/Python_Workspace/deep-learning/others/DocReaderQA/drqa/layers.py", line 11, in <module>
    from sru import SRU
  File "/home/ghostrig/Python_Workspace/deep-learning/deepl_venv/lib/python3.6/site-packages/sru-0.0.1-py3.6.egg/sru/__init__.py", line 2, in <module>
    from .cuda_functional import *
  File "/home/ghostrig/Python_Workspace/deep-learning/deepl_venv/lib/python3.6/site-packages/sru-0.0.1-py3.6.egg/sru/cuda_functional.py", line 355, in <module>
    class SRU_Compute_GPU(Function):
  File "/home/ghostrig/Python_Workspace/deep-learning/deepl_venv/lib/python3.6/site-packages/sru-0.0.1-py3.6.egg/sru/cuda_functional.py", line 357, in SRU_Compute_GPU
    _SRU_PROG = Program(SRU_CODE.encode('utf-8'), 'sru_prog.cu'.encode())
  File "/home/ghostrig/Python_Workspace/deep-learning/deepl_venv/lib/python3.6/site-packages/pynvrtc/compiler.py", line 52, in __init__
    include_names)
  File "/home/ghostrig/Python_Workspace/deep-learning/deepl_venv/lib/python3.6/site-packages/pynvrtc/interface.py", line 200, in nvrtcCreateProgram
    c_char_p(encode_str(src)), c_char_p(encode_str(name)),
  File "/home/ghostrig/Python_Workspace/deep-learning/deepl_venv/lib/python3.6/site-packages/pynvrtc/interface.py", line 54, in encode_str
    return s.encode("utf-8")
AttributeError: 'bytes' object has no attribute 'encode'
Exception ignored in: <bound method Program.__del__ of <pynvrtc.compiler.Program object at 0x7f67dc5a5208>>
Traceback (most recent call last):
  File "/home/ghostrig/Python_Workspace/deep-learning/deepl_venv/lib/python3.6/site-packages/pynvrtc/compiler.py", line 56, in __del__
    self._interface.nvrtcDestroyProgram(self._program)
AttributeError: 'Program' object has no attribute '_program'
```

**Comment by anis016** [comment]
nvm!

If someone falls into error and if you are using CUDA-9.0 then do

> pip install pynvrtc==8.0

this resolved my issue.
