### ISSUE TITLE
Can't import SRU

### ISSUE THREAD

**Issue by MuyuXiaoxiang** [taolei87/sru#72]
Hello, I'm running the example code that you provide, but when I run it, it tells me some error like this. I can't solve it. Could you help me?

Traceback (most recent call last):
File "E:\Anaconda\lib\site-packages\sru\sru_functional.py", line 10, in 
from .cuda_functional import SRU_Compute_GPU
File "E:\Anaconda\lib\site-packages\sru\cuda_functional.py", line 441, in 
class SRU_Compute_GPU(Function):
File "E:\Anaconda\lib\site-packages\sru\cuda_functional.py", line 444, in SRU_Compute_GPU
_SRU_PROG = Program(SRU_CODE, 'sru_prog.cu') # for pynvrtc >= 9.0
File "E:\Anaconda\lib\site-packages\pynvrtc\compiler.py", line 49, in init
self._interface = NVRTCInterface(lib_name)
File "E:\Anaconda\lib\site-packages\pynvrtc\interface.py", line 87, in init
self._load_nvrtc_lib(lib_path)
File "E:\Anaconda\lib\site-packages\pynvrtc\interface.py", line 109, in _load_nvrtc_lib
self.lib = cdll.LoadLibrary(name)
File "E:\Anaconda\lib\ctypes_init.py", line 426, in LoadLibrary
return self.dlltype(name)
File "E:\Anaconda\lib\ctypes_init.py", line 348, in init
self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by MuyuXiaoxiang** [comment]
Sorry, I have solveed the problem. The pynvrtc version I download is not right.
