### ISSUE TITLE
FAILED: sru_cpu_impl.o 

### ISSUE THREAD

**Issue by dosxp** [taolei87/sru#73]
torch is working, but sru cannot work

Warning (from warnings module):
  File "E:\python361\lib\site-packages\torch\utils\cpp_extension.py", line 92
    warnings.warn('Error checking compiler version: {}'.format(error))
UserWarning: Error checking compiler version: Command '['c++']' returned non-zero exit status 1.

Warning (from warnings module):
  File "E:\python361\lib\site-packages\torch\utils\cpp_extension.py", line 118
    warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

Traceback (most recent call last):
  File "E:\python361\lib\site-packages\torch\utils\cpp_extension.py", line 759, in _build_extension_module
    ['ninja', '-v'], stderr=subprocess.STDOUT, cwd=build_directory)
  File "E:\python361\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "E:\python361\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python361\Lib\site-packages\sru\sru_functional.py", line 17, in <module>
    sru_cpu_impl = load(name="sru_cpu_impl", sources=[cpu_source])
  File "E:\python361\lib\site-packages\torch\utils\cpp_extension.py", line 514, in load
    with_cuda=with_cuda)
  File "E:\python361\lib\site-packages\torch\utils\cpp_extension.py", line 682, in _jit_compile
    _build_extension_module(name, build_directory)
  File "E:\python361\lib\site-packages\torch\utils\cpp_extension.py", line 765, in _build_extension_module
    name, error.output.decode()))
RuntimeError: Error building extension 'sru_cpu_impl': [1/2] cl /showIncludes -DTORCH_EXTENSION_NAME=sru_cpu_impl -IE:\python361\lib\site-packages\torch\lib\include -IE:\python361\lib\site-packages\torch\lib\include\TH -IE:\python361\lib\site-packages\torch\lib\include\THC -IE:\python361\Include -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c E:\python361\Lib\site-packages\sru\sru_cpu_impl.cpp /Fosru_cpu_impl.o

FAILED: sru_cpu_impl.o 

cl /showIncludes -DTORCH_EXTENSION_NAME=sru_cpu_impl -IE:\python361\lib\site-packages\torch\lib\include -IE:\python361\lib\site-packages\torch\lib\include\TH -IE:\python361\lib\site-packages\torch\lib\include\THC -IE:\python361\Include -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c E:\python361\Lib\site-packages\sru\sru_cpu_impl.cpp /Fosru_cpu_impl.o

ninja: build stopped: subcommand failed.

**Comment by taolei87** [comment]
It seems a lot people are having issues compiling the cpp code using `ninja`.
This is only needed for inference on CPU. I'll release version that makes this optional..

**Comment by taolei87** [comment]
Have a PR open to address the issue:
https://github.com/taolei87/sru/pull/76
