### ISSUE TITLE
No such file or directory: 'ninja': 'ninja'

### ISSUE THREAD

**Issue by MuyuXiaoxiang** [taolei87/sru#74]
When I run the example you provided, it occurs some errors by the latest version. The problem is below.Can you help me solve it? Thank you!

Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 700, in verify_ninja_availability
    subprocess.check_call('ninja --version'.split(), stdout=devnull)
  File "/home/anaconda3/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/anaconda3/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ninja': 'ninja'

**Comment by taolei87** [comment]
It seems a lot people are having issues compiling the cpp code using `ninja`.
This is only needed for inference on CPU. I'll release version that makes this optional..

**Comment by taolei87** [comment]
Have a PR open to address the issue:
https://github.com/taolei87/sru/pull/76
