### ISSUE TITLE
classification example failed

### ISSUE THREAD

**Issue by zheolong** [taolei87/sru#83]
I've tried to run the classification example, and got some errors.

the command:
```
python train_classifier.py --dataset mr --path ~/Github/sent-conv-torch/data/ --embedding ~/Github/GoogleNews-vectors-negative300.txt --cv 0
```

the ```GoogleNews-vectors-negative300.txt``` file is normal, 3000001 lines, the 2 head lines:

```
3000000 300
</s> 0.001129 -0.000896 0.000319 0.001534 0.001106 -0.001404 -0.000031 -0.000420 -0.000576 0.001076 -0.001022 -0.000618 -0.000755 0.001404 -0.001640 -0.000633 0.001633 -0.001007 -0.001266 0.000652 -0.000416 -0.001076 0.001526 -0.000275 0.000140 0.001572 0.001358 -0.000832 -0.001404 0.001579 0.000254 -0.000732 -0.000105 -0.001167 0.001579 0.000656 -0.000660 0.000003 0.001129 0.000427 -0.000370 -0.001152 0.001266 -0.000004 0.000265 -0.000402 0.000141 -0.000034 0.000759 -0.000519 -0.000071 0.000603 -0.000507 -0.001625 -0.000437 -0.000992 -0.001221 -0.000322 0.000069 -0.001167 -0.000511 0.001411 0.000336 -0.000475 -0.001373 0.000366 -0.001442 -0.000607 0.000801 0.001129 -0.000835 -0.001160 0.000916 0.000523 -0.000328 0.001595 -0.001579 -0.000357 0.000496 0.001015 -0.001099 -0.000166 -0.000142 -0.000261 0.001259 0.000039 0.000169 -0.001030 0.001610 0.000629 0.000418 -0.001350 0.000349 0.001144 -0.001205 -0.001183 0.000950 0.000061 0.000011 -0.000668 0.001244 0.000690 0.000056 -0.000862 -0.001167 0.001213 -0.000805 -0.000877 0.000228 -0.000397 -0.000858 0.000288 -0.001587 0.000484 -0.001122 0.000002 -0.000380 0.000706 -0.001587 0.001625 0.001556 -0.000431 0.000984 0.000904 -0.001396 0.001205 -0.000702 0.000271 -0.001236 0.000690 -0.000843 0.001343 -0.001434 -0.000671 0.001549 -0.001099 0.001190 -0.001427 -0.000683 -0.000786 0.000481 0.000408 -0.000637 0.000145 -0.000977 0.001450 0.000001 -0.001663 -0.000328 0.000629 -0.001434 -0.000341 0.001152 -0.000530 -0.000471 -0.000851 -0.001381 -0.001244 -0.001328 0.001076 0.001320 -0.000303 -0.000037 0.001183 -0.001358 -0.001045 0.000057 -0.001015 0.000433 -0.001572 -0.000091 0.001060 -0.000603 -0.001534 -0.001534 0.000542 0.001335 0.000412 -0.000311 0.000176 -0.000137 -0.000698 -0.000862 -0.001083 -0.000030 0.000801 0.000679 0.000336 -0.001389 0.001350 0.000235 -0.001335 -0.000874 -0.000744 0.001083 0.000061 -0.001266 0.001190 -0.000622 0.000000 0.001274 -0.000984 -0.001549 0.001556 -0.001312 -0.000793 0.001534 0.001297 -0.000180 0.000919 0.001205 0.000771 -0.001656 0.000771 0.001450 -0.001305 0.000610 0.000660 0.001259 0.001419 -0.001221 -0.001511 0.001129 0.001343 0.001663 -0.000572 -0.000557 0.000399 -0.000271 0.000496 0.001610 -0.000706 0.000626 -0.000977 -0.000190 0.000095 -0.000519 -0.000204 -0.000828 -0.000123 0.000763 0.000322 -0.001244 0.000992 0.001060 -0.001411 0.000097 -0.001556 0.000219 -0.000055 -0.000912 -0.001488 0.001366 -0.000843 -0.000420 0.000324 -0.001007 0.000126 -0.000456 0.000193 -0.000269 0.001495 -0.001587 0.000591 -0.001465 0.000965 -0.001282 0.001602 0.001091 -0.001312 0.001091 -0.000511 0.000345 0.001045 -0.000207 0.000904 0.000668 0.001106 -0.000874 -0.000376 -0.000257 -0.000092 0.001434 -0.001183 -0.000087 0.001328 -0.000158 0.001289 -0.000984 -0.000549 -0.001549 0.001373 -0.000061 -0.000824 0.001328 0.001160 0.000568 -0.001564 -0.000123 -0.000086
```

and the error msg:
```
Namespace(batch_size=32, cnn=False, cv=0, d=128, dataset='mr', depth=2, dropout=0.5, embedding='/Users/qjl/Github/GoogleNews-vectors-negative300.txt', lr=0.001, lr_decay=0, lstm=False, max_epoch=100, path='/Users/qjl/Github/sent-conv-torch/data/')

Traceback (most recent call last):
  File "train_classifier.py", line 219, in <module>
    main(args)
  File "train_classifier.py", line 141, in main
    embs = dataloader.load_embedding(args.embedding)
  File "/Users/qjl/Github/sru/classification/dataloader.py", line 211, in load_embedding
    return load_embedding_txt(path)
  File "/Users/qjl/Github/sru/classification/dataloader.py", line 205, in load_embedding_txt
    return words, np.asarray(vals).reshape(len(words),-1)
ValueError: cannot reshape array of size 899999997 into shape (3000000,newaxis)
```

**Comment by zheolong** [comment]
I've fount the reason.

In the txt file, there are 3 lines are abnormal, they have no word in the first column, just as below:

```
  0.037598 -0.042236 -0.021973 0.079102 0.019287 -0.049805 0.084961 -0.036133 -0.041504 0.067871 -0.054932 0.007660 0.028564 0.053467 -0.038330 -0.022461 0.118652 0.030518 -0.091309 0.075195 -0.072266 -0.073730 0.085449 -0.022949 -0.030884 -0.029907 -0.017944 0.022095 0.082520 -0.047607 0.024902 0.048584 -0.051025 -0.073242 0.009766 -0.061279 -0.105957 -0.041748 -0.084961 -0.026001 -0.030640 -0.058350 -0.032715 0.035645 0.008179 0.064941 -0.040771 -0.003250 0.060791 0.056641 -0.004211 0.067383 0.035400 -0.065918 0.075684 0.067871 0.064453 0.019165 -0.012756 -0.094727 0.116699 0.021606 -0.020996 0.022583 -0.021973 -0.067871 -0.088379 0.051270 0.027466 -0.027954 0.074219 -0.030273 -0.071289 -0.036377 -0.169922 0.083008 -0.016724 0.017090 -0.046143 0.045166 -0.012024 0.002762 -0.002472 -0.091309 -0.013000 -0.113770 0.044434 -0.015320 0.022339 -0.043457 -0.011230 -0.068848 0.075684 0.058350 -0.051270 0.052979 0.123047 -0.029419 -0.001755 -0.034668 -0.050049 -0.033936 0.028320 -0.040283 -0.035400 -0.019775 -0.024048 0.041504 -0.053467 -0.004669 -0.080566 -0.002090 0.001381 -0.012695 -0.013916 -0.020630 0.049072 -0.012512 0.036621 -0.057129 0.032715 -0.030029 -0.072754 0.013855 0.023071 -0.059570 -0.112305 0.086914 -0.025757 0.039551 -0.057861 0.025513 -0.042725 0.018799 -0.001877 0.024658 0.041748 0.124512 0.060547 -0.071777 -0.053711 0.020264 0.032959 -0.019897 -0.018799 0.063477 0.053955 -0.082031 0.042969 -0.036133 0.074707 0.027466 -0.016846 -0.005432 0.014832 -0.033936 -0.093750 0.015991 -0.071289 0.028564 -0.034424 0.045898 -0.009888 -0.031738 0.020752 -0.012268 0.074219 0.028564 -0.112793 0.086914 -0.017944 -0.036865 0.047607 -0.069824 0.005798 0.094238 0.014343 -0.034424 -0.051758 0.048828 -0.072266 -0.098633 0.117676 -0.093262 -0.098145 -0.065430 0.010742 -0.034668 0.047363 0.063965 -0.020142 0.023438 -0.006866 -0.023315 -0.109375 -0.009094 -0.022949 -0.043213 0.065430 -0.004761 -0.062500 0.071777 -0.002167 0.071777 0.028076 0.019409 0.054443 0.094238 -0.043701 0.061523 -0.075195 0.027344 -0.004272 0.008179 0.062988 0.026611 -0.010620 0.048828 0.075195 -0.072754 -0.012085 -0.007660 -0.042725 -0.064453 -0.010254 -0.098633 -0.004242 -0.046387 -0.067383 0.051025 -0.031494 0.068848 0.014038 0.013611 0.059082 0.032227 -0.012451 -0.019287 0.056396 0.005585 0.093262 -0.045410 -0.010681 0.090820 -0.016235 0.115723 0.029419 -0.028442 -0.017456 -0.057617 -0.036133 0.092285 -0.037109 0.038818 -0.007996 -0.062012 -0.075195 -0.083008 0.039795 -0.028198 0.035889 -0.013245 -0.000648 -0.107422 0.134766 0.030518 -0.069824 0.022217 0.006775 -0.057617 0.081055 0.044922 0.008118 0.015015 0.067383 0.061035 0.023560 0.042725 0.061279 -0.000740 0.014832 -0.033447 -0.048340 -0.028198 -0.027466 0.032959 0.088379 0.002762 0.045166 0.064941 0.061035 -0.081543 0.025757 0.066895 0.067871 -0.003204 0.036621 -0.010498 0.077148 0.135742
```
