### ISSUE TITLE
classification example failed, invalid index of a 0-dim tensor

### ISSUE THREAD

**Issue by zheolong** [taolei87/sru#85]
Command: 
```
python train_classifier.py --dataset mr --path ~/sent-conv-torch/data/ --embedding ~/GoogleNews-vectors-negative300.txt --cv 0
```

Error:
```
Namespace(batch_size=32, cnn=False, cv=0, d=128, dataset='mr', depth=2, dropout=0.5, embedding='~/GoogleNews-vectors-negative300.txt', lr=0.001, lr_decay=0, lstm=False, max_epoch=100, path='~/sent-conv-torch/data/')

3000000 pre-trained word embeddings loaded.
[WARNING] n_d (128) != word vector size (300). Use 300 for embeddings.
embedding shape: torch.Size([3002319, 300])
270 batches, avg len: 41.2
30 batches, avg len: 42.3
34 batches, avg len: 41.1
train_classifier.py:72: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  x, y = Variable(x, volatile=True), Variable(y)
Traceback (most recent call last):
  File "train_classifier.py", line 219, in <module>
    main(args)
  File "train_classifier.py", line 189, in main
    best_valid, test_err
  File "train_classifier.py", line 104, in train_model
    valid_err = eval_model(niter, model, valid_x, valid_y)
  File "train_classifier.py", line 75, in eval_model
    total_loss += loss.data[0]*x.size(1)
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
```

**Comment by taolei87** [comment]
addressed by this PR #89
